name: Cleanup Artifacts

on:
  workflow_dispatch:  # Trigger on manual dispatch
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI (if needed, comment out if already installed)
        run: sudo apt-get install -y gh  # Comment out if pre-installed

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.SHUBHI_TOKEN_GITHUB }}
        run: gh auth setup-git

      - name: List artifacts before deletion
        env:
          GITHUB_TOKEN: ${{ secrets.SHUBHI_TOKEN_GITHUB }}
        run: |
          echo "Listing all artifacts before deletion:"
          gh api repos/shubhanginannaware/pythonwebapp/actions/artifacts --paginate -q '.artifacts[] | {id: .id, name: .name, created_at: .created_at, expired: .expired}'

      - name: List and delete old artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.SHUBHI_TOKEN_GITHUB }}
        run: |
          days=0  # Temporarily set to 0 for testing, deletes all non-expired artifacts
          date=$(date -d "-$days days" +%Y-%m-%dT%H:%M:%SZ)
          echo "Deleting artifacts older than $days days"
          for artifact_id in $(gh api repos/shubhanginannaware/pythonwebapp/actions/artifacts --paginate -q '.artifacts[] | select(.expired == false and .created_at < "'$date'") | .id'); do
            echo "Deleting artifact $artifact_id"
            gh api --method DELETE repos/shubhanginannaware/pythonwebapp/actions/artifacts/$artifact_id
          done

      - name: List artifacts after deletion
        env:
          GITHUB_TOKEN: ${{ secrets.SHUBHI_TOKEN_GITHUB }}
        run: |
          echo "Listing all artifacts after deletion:"
          gh api repos/shubhanginannaware/pythonwebapp/actions/artifacts --paginate -q '.artifacts[] | {id: .id, name: .name, created_at: .created_at, expired: .expired}'
