name: Cleanup Artifacts

on:
  # Comment out the schedule section for manual execution
  # schedule:
  #   - cron: "*/5 * * * *"  # Runs every 5 minutes (uncomment for scheduled execution)

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI (if needed, comment out if already installed)
        run: sudo apt-get install gh  # Comment out if pre-installed

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.SHUBHI_TOKEN_GITHUB }}
        run: gh auth login --with-token <<< $GITHUB_TOKEN

      - name: List and delete old artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.SHUBHI_TOKEN_GITHUB }}
        run: |
          days=1
          date=$(date -d "-$days days" +%Y-%m-%dT%H:%M:%SZ)
          echo "Deleting artifacts older than $days days"
          for artifact_id in $(gh api repos/shubhanginannaware/pythonwebapp/actions/artifacts --paginate -q '.artifacts[] | select(.expired == false and .created_at < "'$date'") | .id'); do
            echo "Deleting artifact $artifact_id"
            gh api --method DELETE repos/shubhanginannaware/pythonwebapp/actions/artifacts/$artifact_id
          done
